"""Build the two USB layouts the AFS Pro 700 actually reads."""

from __future__ import annotations

import shutil
from pathlib import Path

from .discover import find_aggps_root, short_name
from .languages import DEFAULT_LANGUAGE, validate_language
from .shpio import copy_sidecars, is_z_shape_type, read_header, validate_shape_role


LEAME_TEMPLATES = {
    "es": """AFS Pro 700 — USB generado por AgGPS Studio
=============================================

El paquete completo contiene DOS ZIP listos para el USB. Use UNO solo:

  A) Descomprima {aggps_zip}     → copie AgGPS     → Source = Non Pro 700 1
  B) Descomprima {shapefile_zip} → copie Shapefile → Source = Shapefile

Cada ZIP abre directamente en la única carpeta que necesita copiar. No copie
el ZIP cerrado y no ponga AgGPS y Shapefile juntos en el mismo USB.

------------------------------------------------
VÍA 1 (recomendada) — usar el USB propio del tractor
------------------------------------------------
1. Apague el tractor y retire su USB original.
2. En una computadora, deje la carpeta .cn1 exactamente como está. NO formatee
   el USB y NO copie nada dentro de .cn1.
3. Copie AgGPS o Shapefile a la raíz, al lado de .cn1. Debe quedar, por ejemplo:

   {aggps_boundary}
   {aggps_lines}

   o:

   {shapefile_boundary}
   {shapefile_lines}

4. Devuelva el mismo USB al tractor y encienda. Espere el mensaje de copia
   interna antes de abrir Import2.
5. Data Management → Import2. Importe solo {field} para la primera prueba.
6. Después de importar, un reinicio adicional puede ser normal.

------------------------------------------------
VÍA 2 (alternativa) — usar un segundo pendrive
------------------------------------------------
Use esta vía solo si no quiere conectar el USB original a una computadora.
El segundo pendrive debe ser FAT32, 8–32 GB, y tener solo AgGPS o Shapefile.

1. Apague. Retire el USB .cn1 y coloque el segundo pendrive. Encienda.
2. Espere el mensaje de copia interna. Apague.
3. Retire el segundo pendrive, vuelva a colocar el USB .cn1 y encienda.
4. Abra Import2 recién con el USB .cn1 colocado. Si deja puesto un pendrive sin
   .cn1, Import2 puede no mostrar Grower / Farm / Field.

------------------------------------------------
IMPORTACIÓN
------------------------------------------------
AgGPS:     Source = Non Pro 700 1
Shapefile: Source = Shapefile

1. Boundary / *_Bdy   → Data Type = Boundary
2. LineFeature / *_Taipa → Guidance / Multiswath / Line

Boundary = límite y auto-select GPS. Las taipas son líneas y NUNCA eligen el
campo. El tractor debe estar físicamente dentro del polígono Boundary.

NO copie SurveyPoints. NO cambie coordenadas para ajustar la foto satelital.
{line_only_note}
""",
    "en": """AFS Pro 700 — USB generated by AgGPS Studio
============================================

The complete package contains TWO USB-ready ZIP files. Use only ONE:

  A) Extract {aggps_zip}     → copy AgGPS     → Source = Non Pro 700 1
  B) Extract {shapefile_zip} → copy Shapefile → Source = Shapefile

Each ZIP opens directly to the one folder that must be copied. Do not copy the
closed ZIP and do not place AgGPS and Shapefile together on the same USB drive.

------------------------------------------------
METHOD 1 (recommended) — use the tractor's own USB
------------------------------------------------
1. Power the tractor off and remove its original USB.
2. On a computer, leave the .cn1 folder exactly as it is. DO NOT format the USB
   and DO NOT copy anything inside .cn1.
3. Copy AgGPS or Shapefile to the root, beside .cn1. For example:

   {aggps_boundary}
   {aggps_lines}

   or:

   {shapefile_boundary}
   {shapefile_lines}

4. Return that same USB to the tractor and power on. Wait for the internal-copy
   message before opening Import2.
5. Data Management → Import2. Import only {field} for the first test.
6. One additional restart after importing can be normal.

------------------------------------------------
METHOD 2 (alternative) — use a second USB drive
------------------------------------------------
Use this only if the original USB must not be connected to a computer. The
second drive must be FAT32, 8–32 GB, and contain only AgGPS or Shapefile.

1. Power off. Remove the .cn1 USB and insert the second drive. Power on.
2. Wait for the internal-copy message. Power off.
3. Remove the second drive, reinsert the .cn1 USB, and power on.
4. Open Import2 only after the .cn1 USB is back in place. If a drive without
   .cn1 remains inserted, Import2 may not show Grower / Farm / Field.

------------------------------------------------
IMPORT
------------------------------------------------
AgGPS:     Source = Non Pro 700 1
Shapefile: Source = Shapefile

1. Boundary / *_Bdy      → Data Type = Boundary
2. LineFeature / *_Taipa → Guidance / Multiswath / Line

Boundary drives GPS auto-select. Taipa features are lines and NEVER select the
field. The tractor must be physically inside the Boundary polygon.

DO NOT copy SurveyPoints. DO NOT move coordinates to fit the satellite photo.
{line_only_note}
""",
    "pt-BR": """AFS Pro 700 — USB gerado pelo AgGPS Studio
============================================

O pacote completo contém DOIS ZIPs prontos para o USB. Use apenas UM:

  A) Descompacte {aggps_zip}     → copie AgGPS     → Source = Non Pro 700 1
  B) Descompacte {shapefile_zip} → copie Shapefile → Source = Shapefile

Cada ZIP abre diretamente na única pasta que deve ser copiada. Não copie o ZIP
fechado e não coloque AgGPS e Shapefile juntos no mesmo USB.

------------------------------------------------
MÉTODO 1 (recomendado) — usar o USB do próprio trator
------------------------------------------------
1. Desligue o trator e retire o USB original.
2. Em um computador, deixe a pasta .cn1 exatamente como está. NÃO formate o USB
   e NÃO copie nada dentro de .cn1.
3. Copie AgGPS ou Shapefile para a raiz, ao lado de .cn1. Por exemplo:

   {aggps_boundary}
   {aggps_lines}

   ou:

   {shapefile_boundary}
   {shapefile_lines}

4. Devolva o mesmo USB ao trator e ligue. Aguarde a mensagem de cópia interna
   antes de abrir o Import2.
5. Data Management → Import2. Importe somente {field} no primeiro teste.
6. Uma reinicialização adicional depois da importação pode ser normal.

------------------------------------------------
MÉTODO 2 (alternativo) — usar um segundo pendrive
------------------------------------------------
Use este método somente se não quiser conectar o USB original a um computador.
O segundo pendrive deve ser FAT32, 8–32 GB, e conter apenas AgGPS ou Shapefile.

1. Desligue. Retire o USB .cn1 e coloque o segundo pendrive. Ligue.
2. Aguarde a mensagem de cópia interna. Desligue.
3. Retire o segundo pendrive, recoloque o USB .cn1 e ligue.
4. Abra o Import2 somente depois de recolocar o USB .cn1. Se um pendrive sem
   .cn1 continuar conectado, o Import2 pode não mostrar Grower / Farm / Field.

------------------------------------------------
IMPORTAÇÃO
------------------------------------------------
AgGPS:     Source = Non Pro 700 1
Shapefile: Source = Shapefile

1. Boundary / *_Bdy      → Data Type = Boundary
2. LineFeature / *_Taipa → Guidance / Multiswath / Line

Boundary controla a seleção automática por GPS. As taipas são linhas e NUNCA
selecionam o talhão. O trator deve estar dentro do polígono Boundary.

NÃO copie SurveyPoints. NÃO mova coordenadas para ajustar a foto de satélite.
{line_only_note}
""",
}

INDEX_COPY = {
    "es": ("Cliente\tEstablecimiento\tLote\tNombre_USB\tLímite\tTaipas", "sí", "no"),
    "en": ("Grower\tFarm\tField\tUSB_name\tBoundary\tTaipa_lines", "yes", "no"),
    "pt-BR": ("Cliente\tFazenda\tTalhão\tNome_USB\tLimite\tTaipas", "sim", "não"),
}

LINE_ONLY_COPY = {
    "es": (" van solo en AgGPS (son taipas sin límite). No usarlos para auto-select."),
    "en": (" are available only in AgGPS (taipa lines without a boundary). Do not use them for auto-select."),
    "pt-BR": (" ficam somente no AgGPS (são taipas sem limite). Não use esses grupos para seleção automática."),
}

CONJUNCTIONS = {"es": " y ", "en": " and ", "pt-BR": " e "}


def build_usb_tree(
    extract_dir: Path,
    fields: list[dict],
    dest: Path,
    *,
    language: str = DEFAULT_LANGUAGE,
    artifact_names: dict[str, str] | None = None,
) -> dict:
    language = validate_language(language)
    for rec in fields:
        if not rec.get("boundary") or not rec["boundary"].exists():
            raise ValueError(f"missing required Boundary.shp for field: {rec['field']}")
        if not rec.get("lines") or not rec["lines"].exists():
            raise ValueError(f"missing required LineFeature.shp for field: {rec['field']}")
        validate_shape_role(rec["boundary"], "Boundary")
        validate_shape_role(rec["lines"], "LineFeature")

    dest.mkdir(parents=True, exist_ok=True)

    ag_src = find_aggps_root(extract_dir)
    if ag_src and (ag_src / "Data").exists():
        _pruned_copy_aggps(ag_src, dest / "A_AgGPS" / "AgGPS")

    shp_dir = dest / "B_Shapefile" / "Shapefile"
    shp_dir.mkdir(parents=True, exist_ok=True)
    used: set[str] = set()
    mapping = []
    for rec in fields:
        slug = short_name(rec["field"], used, farm=rec["farm"])
        mapping.append((rec, slug))
        copy_sidecars(rec["boundary"], shp_dir / f"{slug}_Bdy.shp")
        copy_sidecars(rec["lines"], shp_dir / f"{slug}_Taipa.shp")

    index_header, yes, no = INDEX_COPY[language]
    index_lines = [index_header]
    for rec, slug in mapping:
        index_lines.append(
            f"{rec['client']}\t{rec['farm']}\t{rec['field']}\t{slug}\t"
            f"{yes if rec.get('boundary') else no}\t"
            f"{yes if rec.get('lines') else no}"
        )
    (dest / "INDICE_CAMPOS.txt").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    line_only = _line_only_names(ag_src) if ag_src else []
    (dest / "LEAME.txt").write_text(
        _build_leame(
            mapping,
            line_only,
            language=language,
            artifact_names=artifact_names,
        ),
        encoding="utf-8",
    )
    return {"mapping": mapping, "shp_dir": shp_dir, "line_only": line_only}


def _build_leame(
    mapping: list[tuple[dict, str]],
    line_only: list[str],
    *,
    language: str = DEFAULT_LANGUAGE,
    artifact_names: dict[str, str] | None = None,
) -> str:
    language = validate_language(language)
    if mapping:
        rec, slug = mapping[0]
        aggps_base = f"E:\\AgGPS\\Data\\{rec['client']}\\{rec['farm']}\\{rec['field']}"
        field = rec["field"]
    else:
        slug = "<Campo>"
        aggps_base = "E:\\AgGPS\\Data\\<Grower>\\<Farm>\\<Campo>"
        field = {"es": "un lote", "en": "one field", "pt-BR": "um talhão"}[language]
    if line_only:
        names = CONJUNCTIONS[language].join(f"`{name}`" for name in line_only)
        line_only_note = f"\n{names}{LINE_ONLY_COPY[language]}"
    else:
        line_only_note = ""
    artifact_names = artifact_names or {
        "aggps": "AgGPS.zip",
        "shapefile": "Shapefile.zip",
    }
    return LEAME_TEMPLATES[language].format(
        aggps_zip=artifact_names["aggps"],
        shapefile_zip=artifact_names["shapefile"],
        aggps_boundary=f"{aggps_base}\\Boundary.shp",
        aggps_lines=f"{aggps_base}\\LineFeature.shp",
        field=field,
        shapefile_boundary=f"E:\\Shapefile\\{slug}_Bdy.shp",
        shapefile_lines=f"E:\\Shapefile\\{slug}_Taipa.shp",
        line_only_note=line_only_note,
    )


def _line_only_names(aggps_root: Path) -> list[str]:
    data_root = aggps_root / "Data"
    names = set()
    for lines in data_root.rglob("LineFeature.shp"):
        if (lines.parent / "Boundary.shp").exists():
            continue
        try:
            header = read_header(lines)
        except Exception:
            continue
        if not is_z_shape_type(header.get("type") or header.get("type_code", 0)):
            names.add(lines.parent.name)
    return sorted(names, key=str.casefold)


def _pruned_copy_aggps(src: Path, dst: Path) -> None:
    """Copy Trimble AgGPS tree preserving byte-identical Boundary/LineFeature,
    but prune case-insens SurveyPoints*, Z shapefile families +sidecars, and .prj/.cpg.
    """
    dst.mkdir(parents=True, exist_ok=True)
    # identify Z shape bases (by header type) to skip whole family
    z_bases: set[tuple[Path, str]] = set()
    for shp in (path for path in src.rglob("*") if path.is_file() and path.suffix.lower() == ".shp"):
        try:
            hdr = read_header(shp)
            if is_z_shape_type(hdr.get("type") or hdr.get("type_code", 0)):
                rel_parent = shp.parent.relative_to(src)
                z_bases.add((rel_parent, shp.stem.lower()))
        except Exception:
            # malformed shp: treat as z-unsafe for safety (will be rejected upstream anyway)
            rel_parent = shp.parent.relative_to(src)
            z_bases.add((rel_parent, shp.stem.lower()))

    for p in src.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(src)
        # case-insensitive SurveyPoints anywhere in path
        if any(part.lower().startswith("surveypoints") for part in rel.parts):
            continue
        name_l = p.name.lower()
        # always drop .prj .cpg sidecars
        if name_l.endswith((".prj", ".cpg")):
            continue
        # drop if part of Z family
        stem_l = p.stem.lower()
        if (rel.parent, stem_l) in z_bases:
            continue
        dstd = dst / rel
        dstd.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(p, dstd)
